  
spring:
  h2:
    console:
      enabled: true
      path: /h2console
      
  datasource:
    url: jdbc:h2:~/productmicroservice
    driver-class-name: org.h2.Driver 
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.generate_statistics : true

eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka

  instance:
   hostname: 192.168.99.100 
   
   
management:
  server:
    port: 1234

  endpoints:
    web:
      exposure:
        include: "*"    
        
welcome:
    message: "Refreshed 4!!!! from local to GIT repo!!!!"        
  